### ISSUE TITLE
FM Ansible Snippets

### ISSUE THREAD

**Issue by xaaaaav** [dataiku/dss-code-samples#16]
The FE US team has discussed starting to bring together FM ansible snippets and be able to share publicly with customers. Raising this as an issue here to start the discussion and to see if it makes sense adding them here or if there is a better place for them.

We were thinking of creating some high-level directories here in the repo, one for DSS code snippets and one for FM ansible snippets. Thoughts?

@hrjn
@cstenac
@JedIV
@jbelafa

**Comment by hrjn** [comment]
@xaaaaav I would prefer having a distinct private repository for the Ansible stuff, and share its content on a per-use-case basis with customers. FM setup actions are more "critical" than the small example snippets of this repository, and their target users are different.

For the record, we do not plan on actively and officially support the content of this repository, this is just a list of examples regarding how to use the public API, which is not directly affiliated with our reference documentation.

**Comment by hrjn** [comment]
Closing this for now as the Ansible stuff will very likely be collected elsewhere first.
